import {
  Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, UpdateDateColumn,
  ManyToOne, JoinColumn, Index,
} from 'typeorm';
import { StandardEnum } from '../../types/standard.enum';
import { ProductEntity } from '../../products/entities/product.entity';

@Entity('documents')
@Index(['designation'], { unique: true })
@Index(['productId']) 
export class DocumentEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ unique: true })
  designation: string; // Full generated designation

  @Column()
  productId: string; // Foreign key

  @ManyToOne(() => ProductEntity, (product) => product.documents, { 
    onDelete: 'RESTRICT', // Prevent product deletion if documents exist; handle in service layer
    nullable: false 
  })
  @JoinColumn({ name: 'productId' })
  product: ProductEntity;
  
  @Column()
  productNameSnapshot: string; // Name of the product at the time of document creation

  @Column()
  docTypeCode: string; // e.g., "00", "СБ", "ТЗ"

  @Column()
  docTypeName: string; // Standard or custom name of the document type, stored at creation

  @Column({ nullable: true })
  customDocName?: string; // User-defined name for this specific document instance

  @Column({
    type: 'enum',
    enum: StandardEnum,
    comment: 'Standard of the parent product this document belongs to'
  })
  selectedStandard: StandardEnum;

  @CreateDateColumn()
  assignmentDate: Date;

  @Column({ type: 'text', nullable: true })
  comment?: string;

  // ESPD Document Specific Details
  @Column({ type: 'jsonb', nullable: true })
  espdDetails?: {
    espdSoftwareType: string;       // "ПО" or "ПАК"
    espdBaseDocRevision: string;    // "01"-"99"
    espdDocNumberByType: string;    // "01"-"99"
    espdDocPartNumber?: string;     // "1"-"9"
  };

  // ESKD Document Specific Details
  @Column({ type: 'jsonb', nullable: true })
  eskdDetails?: {
    eskdDocRevision?: string;   // "01"-"99"
    eskdDocPartNum?: string;    // User-defined
  };

  // GOST 34 Document Specific Details
  @Column({ type: 'jsonb', nullable: true })
  gost34Details?: {
    gost34DocSequenceNum: string; // "01"-"99", generated by backend if not provided by user
    gost34RevisionNum?: string;   // "2"-"9"
    gost34PartNum?: string;       // "1"-"9"
    gost34MachineReadable: boolean; // .М
  };

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
